language: java
jdk:
- oraclejdk8
before_install: "-chmod +x gradlew"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
deploy:
  provider: script
  script: gradle bintrayUpload
  skip_cleanup: true
  on:
    tags: true
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - secure: L6flhO68m+gedzHf1MhcbIn4a4+hfEm/8jASotbQp0vV6SQRoRis18lYdnoFedHg5/8LbqUe28tp7mkHfCk+Z8Wf8Aa37O8GQ7EHwcboeS8NVNhAc2GL3uqKX9BwLFJX8vCF2if/SBd13GMEtW51Z/e5GDOoawCVDcCbcRZYpB2p6pnmCQGvXSkJl1/20pl/6Hmllbv5tyQgrP6dCbyPtdN611stKaIO+XTVZwbnhqtLM/I7QYy/NvS4m6Ul4iIaK5Owc5whkRxFTdQgSIIEOMqY1jZEnYbZNrayFCQx+VY7RJXjYiYeTzXYqP0NBF/Ya5Y3+BIXSHR8zDVNIJ0EXBnIrYVAg1yNisbR9Jzt2iQtbOEtPgYMLQfD3i54iULlX4KE418L9APq2D6mX9M4Mt9pA4fRww/fS0f+t5bpcnAiOr9isOYnejFnCqOrAwphkAJeFvrsS/tGjAwDDyxs4pSEYhEeM0+MMJZclsOfpu/K2LQC3Gjn1Y3iNdivwb/eDbjdjT2q5XYV4rH1/KnxCDAzDhg1xJXA73YPbf+gpqjjhnNbkhIRC0t/BSC+NU4chg70mxrOpBQcMBnx6p03f/LZFuGMHUrMh2RptmQtRjfIQKwbOyCte80EZXKb130M01wZvqj+R82dW0MbgF2087lFCLOCzXeCrN/d027hUe8=
  - secure: LgWTrXIUfW8roF2aW64vCEUnNEPs2kgWR+CH8WpPP/wFqMbZ0OL41aC43g+bnfacwb/a0Q+rIM0kQ/fHQlDEkqHEDfEfEyvcLOFiLAuRVgZgV2SjZdQLYipe6ZqrXapz4XEC3507sxURsS9I3sOpPt14dNc9FbPsoM/kpBsGJmAqiZC9DgEJmV4o1tHfkzXSs6Wop0LQXpHPfzQP88OK674ZbR7QcjhhzPFQwEnDLSmnv3R5zKGDylrjykW1VRyuZ3rwGg6bNpRxA5psGgiEapOsO4NfRBBIM6SB/n66B+uSeHwLc3SGmjahyC130gl6HgdarSmKhDABMkLeyUicAAnyy6To2/lF6bEMlzZkOsZVN+HKXKtLAfW90HYH7P3A7riAHDcN+iYO7AyPVi0Wf4Wm/IKxtsyvS2OHdMClv0EYpD4GRfPOJ8XiU3lk4yytGvqlsnND1DIY4F9IkQHK+wMg8oDSTEr9qkr+ky5VwKPhsBfevmiYb48FJTFmDLibQ0qVbk6/x0Dqw45gGwByLZ/Wifv2CYrY4bjx2Czf3Q9Cqapd4iWf0QzhTodBHwZoXHI4ScxojmUYFLj4XDPNkgI/KmLgaWvbXwRso28LbXh3DMrcgjoICpUNB5cmBcfx7mpJOJNi/8PGwX3gKv9MLhGxzrtRm6gFBQZl4SUBoSY=
